### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mecqor** [JonasBernard/FakeStandby#11]
This app does not work!
I ran this app on three different phones, but it only worked for 1 minute.

Tested on: Galaxy J7 2017, Galaxy J7 Core, Galaxy A30s

Android: 8, 9, 10

**Comment by JonasBernard** [comment]
This is an issue I never had before. What app did you have open when using the app?

**Comment by mecqor** [comment]
I do not remember correctly; But this did not work on several programs.

**Comment by padrino-x** [comment]
I think this has to do with tha app running in front allowing the phone to lock itself.
So when the screen dims right before locking the overlay is closed.
E.g. using it with "here maps/we go".
When you start the app it still allows the phone to lock itsself, during navigation this is prevented and FakeStandby works.

**Comment by JonasBernard** [comment]
Yes, that is possible. I therefore added to the app, that it requests an wake lock. This means, it says "Hey phone dont lock right now, even if nothing happens". Maybe this request is not accepted by the system for background jobs like FakeStandby

**Comment by JonasBernard** [comment]
Okay I fixed this. The fix will be in the next release.

**Comment by padrino-x** [comment]
Hi, just installed 1.3.0 from fdroid, and it still seems to be a problem.
Just tried it on the home sceen.
When it is time to dim the screen FakeStandby is deactivated.

**Comment by padrino-x** [comment]
🙋🏻‍♂️

Anyone here to confirm that 1.3.0 is still not working?
Or does "app acquires wake lock" in release notes mean something different? 🤔😊
